### ISSUE TITLE
get https://signaling.arukascloud.io/stun no such host

### ISSUE THREAD

**Issue by teguhteja** [nobonobo/ssh-p2p#5]
i found error while running in folder ssh-p2p
go run main.go server -key="<my new key>" -dial="127.0.0.1:22"

2017/08/01 11:26:11 Get https://signaling.arukascloud.io/stun: dial tcp: lookup signaling.arukascloud.io on 127.0.0.1:53 no such host 

is it correct my command ? or the host is dead ? 
because i check in dnsdumpster there is no host

**Comment by nobonobo** [comment]
Sorry, arukascloud.io service is currently suspended. It is necessary to operate a SignalingServer in a place accessible from multiple peers.

SignalingServer implementation: https://github.com/nobonobo/p2pfw/tree/master/signaling/server

**Comment by nobonobo** [comment]
New signaling server deployed!
default url fixed from signaling.arukascloud.io to signaling.irieda.com

**Comment by nobonobo** [comment]
#7 updated signaling service change to https://nobo-signaling.appspot.com
signaling server implementation:  https://github.com/nobonobo/ssh-p2p/tree/master/signaling/gae
